### ISSUE TITLE
Purge the binaries from the repository

### ISSUE THREAD

**Issue by cadencemarseille** [thehydroimpulse/jiter#1]
Hi Daniel,

There were a few binaries that were committed to the repository, but later deleted (64-bit Mach-O binaries from the looks of it).  It would be really good to purge these from the repository.

GitHub has a page on how to do this:  https://help.github.com/articles/remove-sensitive-data
But, `git filter-branch` is a bit confusing, in my opinion.

I took the liberty of creating a [`reposurgeon`](http://www.catb.org/~esr/reposurgeon/) script that gets rid of the binaries and the `.vagrant` folder:

<pre>
read
10..15 expunge main
20..22 expunge jit src/jiter
25..$ expunge bin/jittest
57..$ expunge /^\.vagrant\//
rebuild
</pre>

This purges the `main` binaries of 2cb2989 through 51cbf74, then purges the `jit` and `src/jiter` binaries of 4e4c6f5 and fe681f4, then purges the `bin/jittest` binaries of fe1b27d through e1ca74f, and finally purges the `.vagrant` folder of b956648, finally dropping the e1ca74f commit.

To use, install `reposurgeon` (`brew install reposurgeon` on Mac using [Homebrew](http://brew.sh/)).  `cd` into the checkout of jiter, and start reposurgeon.  At the interactive command interpreter, paste in the script above.  Then Ctrl+C to quit.

You will then need to force update the jiter repository:

<pre>
git remote add origin https://github.com/TheHydroImpulse/jiter.git
git push -f origin master
</pre>

Note that reposurgeon creates a backup copy of the original repository if anything goes wrong.

I uploaded the resulting repository to https://github.com/cadencemarseille/jiter

**Comment by thehydroimpulse** [comment]
@cadencemarseille Thanks for the tip. I'll definitely put that on the list todo.

**Comment by thehydroimpulse** [comment]
@cadencemarseille Thanks again for the info. I've purged the binaries from the repo.
